[package]
name = "root-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
paste = "1.0.14"

[build-dependencies]
bindgen = "0.69.1"
cmake = "0.1.50"
regex = "1.10.2"
