RRS_CLASS(TH1);
RRS_CLASS_PARENT(TH1, TNamed);
RRS_CLASS_PARENT(TH1, TAttLine);
RRS_CLASS_PARENT(TH1, TAttFill);
RRS_CLASS_PARENT(TH1, TAttMarker);

#ifdef ROOT_RS_INCLUDE_INCLUDES
#include <TH1.h>
#endif

#ifdef ROOT_RS_INCLUDE_FUNCTIONS
//RRS_STRUCT(TH1) RRS_METHOD(TH1, clone)(RRS_STRUCT(TH1) RRS_CONST_REF self);
//RRS_STRUCT(TH1) RRS_METHOD(TH1, clone_with_name)(RRS_STRUCT(TH1) RRS_CONST_REF self, const char* RRS_CONST_REF new_name);
#endif