name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
    inputs:
      choosen-os:
        required: true
        description: "Choose the OS to run the workflow on"
        type: choice
        options:
          - ubuntu-latest
          - windows-latest

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: "${{ inputs.choosen-os }}"

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Build release
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose
