name: Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    #- name: Install dependencies
    #  run: |
    #    sudo apt update
    #    sudo apt install nlohmann-json3-dev
    - name: install nlohmann json from git release
      run: |
        cd ~
        wget https://github.com/nlohmann/json/archive/refs/tags/v3.11.3.tar.gz
        tar -xzf v3.11.3.tar.gz
        cd json-3.11.3
        mkdir build
        cd build
        cmake -DJSON_BuildTests=OFF ..
        make
        sudo make install
    - name: download-root
      run: |
        cd ~
        wget https://root.cern/download/root_v6.30.02.Linux-ubuntu23.04-x86_64-gcc12.3.tar.gz
        tar -xzf root_v6.30.02.Linux-ubuntu23.04-x86_64-gcc12.3.tar.gz
        source ~/root/bin/thisroot.sh
    - name: Configure CMake for C bindings
      working-directory: ${{github.workspace}}/root-rs-c-bindings
      run: |
        source ~/root/bin/thisroot.sh
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=test_install_dir
    - name: Build C bindings
      working-directory: ${{github.workspace}}/root-rs-c-bindings
      run: |
        source ~/root/bin/thisroot.sh
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Test C bindings
      working-directory: ${{github.workspace}}/build
      run: |
        source ~/root/bin/thisroot.sh
        ctest -C ${{env.BUILD_TYPE}}
    - name: Rust Build
      run: |
        source ~/root/bin/thisroot.sh
        cargo build --verbose
    - name: Rust Test
      run: |
        source ~/root/bin/thisroot.sh
        cargo test --verbose
